config/routes.rb
EmployeeTracker::Application.routes.draw do
 get "admin/index"
  
  get "admin/employee_status"
  
   get "admin/show"
   
      get "admin/download"

  
     match "admin/update_dept",:controller=>"admin",:action=>"update_dept",:method=>:post
  
    get "admin/showdept"
     get "admin/adddept"
    
  resources :employees

  resources :companies

  devise_for :users

   root :to => 'companies#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :address, :email, :name
end

app/models/department.rb
class Department < ActiveRecord::Base
  attr_accessible :description, :name
  
  belongs_to:employee
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :departmentname, :email, :name, :occupation, :salary,:status,:user_id,:department_id,:gender,:profile_status,:image	
  
  belongs_to :user
  
  mount_uploader :image,ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me ,:role, :gender
  # attr_accessible :title, :body
  
  has_one :employee
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  include Employeenew

  def index
    @employee = Employee.all
    
    
    p "module based record"
    
    
  end
  
  def employee_status
    @emp = Employee.find(params[:id])
    if @emp.status == "active"
    
    Employee.update(params[:id],{:status=>"inactive"} )
    else
        Employee.update(params[:id],{:status=> "active"} )
        
     end    
     redirect_to admin_index_path
     
  end
  
  def show
    @emp = Employee.find(params[:id])
    
  end
  
  def download
     send_file "#{Rails.root}/public/quick_openrp.tar.gz"
  end
  
  
  
  def adddept
  
   @department=Department.all
   p @department
   respond_to do |format|
     format.js
   end 
     
   def update_dept
   
   	@dept = Department.find(params[:dept]) 
   	
   	respond_to do |format|
   	@emp_update = Employee.update({:department_id => @dept.id},{:id=> @dept.employee.id})
   	  format.js
   	end
   redirect_to admin_index_path
   
  end  
  
 end
  
end #controller ends

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
  require 'employeenew'


  
  def after_sign_in_path_for(resource)
     if current_user.role != "admin"  
     
        "/employees/new"
      
       
    else
     "/admin/index"
    end
  end

  
  
  # this method is to identify user role
  def admin_role
  p "methoddddddd"
  
   p current_user.role
    #@user=User.find_by_id(current_user.id)
     # if @user.role != "admin"  

      #  redirect_to "admin/index"
      #else
      
      # p "<<<<<<<<<<<<<"
  
     # end


  end
  
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController


  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
def capitalize(string)
    string.capitalize
  end


def created_at
    model.created_at.strftime("%b %d")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/_adddept.html.erb
<%= form_tag('/admin/update_dept' ,:remote => true) %>
<%#= form_tag({:controller => "admin", :action => "update_dept"},:remote => true)%>
<%= select_tag "dept", options_from_collection_for_select(@department, "id", "name")%>

<%= submit_tag "Submit" %>

app/views/admin/adddept.js.erb
jQuery("#department").html("<%= escape_javascript(render(:partial => 'adddept'))%>");

app/views/admin/index.html.erb
<%= link_to "Sign out", destroy_user_session_path, :method => :delete,:style=>"float:right" %>

<table border ="2" >
<tr><th>Name</th><th>Salary</th><th>Occupation</th><th>Email</th><th>Status</th><th>Show link</th><th>Salary slip</th></tr>


<% @employee.each do |emp| %>

<tr><td><%=capitalize emp.name %></td>
<td><%= emp.salary %></td>
<td><%= emp.occupation %></td>
<td><%= emp.email %></td>
<td>

<% if emp.status == "active" %>
   <%= link_to "inactive", admin_employee_status_path(:id=>emp.id) %>
<% else %>
   <%= link_to "active",admin_employee_status_path(:id=>emp.id) %>
<% end %>
</td>
<td><%= link_to "show" ,admin_show_path(:id=>emp.id)%></td>

<td><%= link_to "Download" ,admin_download_path(:id=>emp.id)%></td>
</tr>
		
<% end if @employee%></table>	

app/views/admin/show.html.erb
<div id="main">
<%= link_to "Sign out", destroy_user_session_path, :method => :delete,:style=>"float:right" %>

<table border ="2" >
<tr><th>Name</th><th>Salary</th><th>Occupation</th><th>Email</th><th>Status</th><th>Add Department</th></tr>


<tr><td><%= @emp.name %></td>
<td><%= @emp.salary %></td>
<td><%= @emp.occupation %></td>
<td><%= @emp.email %></td>
<td><%= @emp.status %></td>
<td><%= link_to "Add Dept" ,{:controller=>"admin",:action=>"adddept",:id=>@emp.id},:remote=>true %></td>
</tr>
</div>
<%#= link_to "Vote Yes", {:controller=>"widgets", :action => 'vote',:id=>widget, :vote=>true}, :remote=> true, :class=>"yes-button" %>


 <div id="department" style="float:right; padding:220px 900px 0px 0px;">

 </div>



</table>	

app/views/admin/update_dept.js.erb
jQuery("#department").hide();

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete,:style=>"float:right" %>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @companies.each do |company| %>
  <tr>
    <td><%= company.name %></td>
    <td><%= company.email %></td>
    <td><%= company.address %></td>
    <td><%= link_to 'Show', company %></td>
    <td><%= link_to 'Edit', edit_company_path(company) %></td>
    <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @company.name %>
</p>

<p>
  <b>Email:</b>
  <%= @company.email %>
</p>

<p>
  <b>Address:</b>
  <%= @company.address %>
</p>


<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/employees/_form.html.erb
<%= form_for(@employee,:html=>{:multipart=>true}) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :occupation %><br />
    <%= f.text_field :occupation %>
  </div>
  <div class="field">
    <%= f.label :salary %><br />
    <%= f.text_field :salary %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Occupation</th>
    <th>Salary</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.name %></td>
    <td><%= employee.occupation %></td>
    <td><%= employee.salary %></td>
    <td><%= employee.email %></td>
    <td><%= link_to 'Show', employee %></td>
    <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
    <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @employee.name %>
</p>

<p>
  <b>Occupation:</b>
  <%= @employee.occupation %>
</p>

<p>
  <b>Salary:</b>
  <%= @employee.salary %>
</p>

<p>
  <b>Email:</b>
  <%= @employee.email %>
</p>

<p>
  <b>image:</b>
  <%= image_tag(@employee.image_url) %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmployeeTracker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application","prototype.js","rails.jquery.js","jquery.min.js","jquery.js"%>
  <%#= javascript_include_tag :defaults %>


  <%= csrf_meta_tags %>
</head>
<body>
<p><%= notice %></p>

<p><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>